const NAVIGATION_COMPONENT = {
  DRAWER_NAV: 'DRAWER_NAV',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'Home',
  ARCHIVED_SCREEN: 'Archived',
  TRASH_SCREEN: 'Trash',
  CREATE_NOTE_SCREEN: 'Create New Note',
  DETAIL_NOTE_SCREEN: 'Detail Note',
};

export default NAVIGATION_COMPONENT;
